/*
 * IncludeMcuLibConfig.h
 */

#ifndef SRC_INCLUDEMCULIBCONFIG_H_
#define SRC_INCLUDEMCULIBCONFIG_H_

#define McuLib_CONFIG_SDK_VERSION_USED  McuLib_CONFIG_SDK_MCUXPRESSO_2_0

#define McuLib_CONFIG_CPU_IS_ARM_CORTEX_M    (0)
#define McuLib_CONFIG_CPU_IS_RISC_V          (1)

#define McuLib_CONFIG_SDK_USE_FREERTOS          (0)

#define McuLib_CONFIG_SDK_VERSION_MAJOR   (2)
#define McuLib_CONFIG_SDK_VERSION_MINOR   (2)
#define McuLib_CONFIG_SDK_VERSION_BUILD   (0)


#endif /* SRC_INCLUDEMCULIBCONFIG_H_ */
