package:
  name: nxp_additional_clibs
  version: "12.2.rel1"

source:
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-win32.zip # [win]
  sha256: a733135708418bda29bcd4f5e3247fea83c4012d4a3c2704fc966696b99a1b4f # [win]]
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-linux.tar.xz # [linux64]
  sha256: fbf00b2ede5e230f2d8cecb13545fb501aec62eb5e813294e9dbdff194745b2b # [linux64]
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-mac.tar.xz # [osx]
  sha256: 6072e6025ede54d1e68b41a0…f7f5cadc0cd53cf65e8ae7a # [osx]
  
build:
  string: '0'

about:
  home: https://www.nxp.com
  license: NXP
  summary: Additional NXP libraries and header files for Arm GNU Toolchain.
  