perl avstack.pl ^
Debug\Sources\Application.o ^
Debug\Sources\Events.o ^
Debug\Sources\Joystick.o ^
Debug\Sources\ProcessorExpert.o ^
Debug\Sources\RNet_App.o ^
Debug\Sources\Shell.o ^
Debug\Sources\ProcessorExpert.o ^
Debug\Generated_Code\AS1.o ^
Debug\Generated_Code\ASerialLdd1.o ^
Debug\Generated_Code\ASerialLdd2.o ^
Debug\Generated_Code\BitIoLdd1.o ^
Debug\Generated_Code\BitIoLdd2.o ^
Debug\Generated_Code\BitIoLdd3.o ^
Debug\Generated_Code\BitIoLdd8.o ^
Debug\Generated_Code\BitIoLdd9.o ^
Debug\Generated_Code\BT1.o ^
Debug\Generated_Code\CD2.o ^
Debug\Generated_Code\CLS1.o ^
Debug\Generated_Code\Cpu.o ^
Debug\Generated_Code\croutine.o ^
Debug\Generated_Code\CS1.o ^
Debug\Generated_Code\event_groups.o ^
Debug\Generated_Code\FAT1.o ^
Debug\Generated_Code\ff.o ^
Debug\Generated_Code\FRTOS1.o ^
Debug\Generated_Code\FX1.o ^
Debug\Generated_Code\GI2C1.o ^
Debug\Generated_Code\heap_1.o ^
Debug\Generated_Code\heap_2.o ^
Debug\Generated_Code\heap_3.o ^
Debug\Generated_Code\heap_4.o ^
Debug\Generated_Code\heap_5.o ^
Debug\Generated_Code\HF1.o ^
Debug\Generated_Code\I2C.o ^
Debug\Generated_Code\Inhr1.o ^
Debug\Generated_Code\Inhr2.o ^
Debug\Generated_Code\KEY1.o ^
Debug\Generated_Code\KIN1.o ^
Debug\Generated_Code\LED1.o ^
Debug\Generated_Code\LED2.o ^
Debug\Generated_Code\LED3.o ^
Debug\Generated_Code\LEDpin1.o ^
Debug\Generated_Code\LEDpin2.o ^
Debug\Generated_Code\LEDpin3.o ^
Debug\Generated_Code\list.o ^
Debug\Generated_Code\minGlue-FatFs.o ^
Debug\Generated_Code\MINI1.o ^
Debug\Generated_Code\minIni.o ^
Debug\Generated_Code\PE_LDD.o ^
Debug\Generated_Code\Pins1.o ^
Debug\Generated_Code\port.o ^
Debug\Generated_Code\queue.o ^
Debug\Generated_Code\RTOSTRC1.o ^
Debug\Generated_Code\SD1.o ^
Debug\Generated_Code\SEGGER_RTT.o ^
Debug\Generated_Code\SEGGER_RTT_Printf.o ^
Debug\Generated_Code\Serial1.o ^
Debug\Generated_Code\SM1.o ^
Debug\Generated_Code\SS1.o ^
Debug\Generated_Code\tasks.o ^
Debug\Generated_Code\timers.o ^
Debug\Generated_Code\TmDt1.o ^
Debug\Generated_Code\TMOUT1.o ^
Debug\Generated_Code\trcKernelPort.o ^
Debug\Generated_Code\trcRecorder.o ^
Debug\Generated_Code\TRG1.o ^
Debug\Generated_Code\UTIL1.o ^
Debug\Generated_Code\WAIT1.o ^
Debug\Static_Code\System\CPU_Init.o ^
Debug\Static_Code\System\Peripherals_Init.o ^
Debug\Static_Code\System\Vectors.o ^
Debug\Project_Settings\Startup_Code\startup.o ^
 > stackUsage.txt