/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : OutputRB1.c
**     Project     : FRDM-KL27Z_McuOnEclipseLib
**     Processor   : MKL25Z128VLK4
**     Component   : RingBuffer
**     Version     : Component 01.051, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-05-11, 11:56, # CodeGen: 137
**     Abstract    :
**         This component implements a ring buffer for different integer data type.
**     Settings    :
**          Component name                                 : OutputRB1
**          SDK                                            : MCUC1
**          Reentrant                                      : yes
**          Critical Section                               : CS1
**          Buffer Elements                                : 10
**          Element Size                                   : 1 Byte
**     Contents    :
**         Clear           - void OutputRB1_Clear(void);
**         Put             - uint8_t OutputRB1_Put(OutputRB1_ElementType elem);
**         Get             - uint8_t OutputRB1_Get(OutputRB1_ElementType *elemP);
**         Peek            - uint8_t OutputRB1_Peek(OutputRB1_BufSizeType index, OutputRB1_ElementType...
**         Update          - uint8_t OutputRB1_Update(OutputRB1_BufSizeType index, OutputRB1_ElementType...
**         Putn            - uint8_t OutputRB1_Putn(OutputRB1_ElementType *elem, OutputRB1_BufSizeType nof);
**         Getn            - uint8_t OutputRB1_Getn(OutputRB1_ElementType *buf, OutputRB1_BufSizeType nof);
**         Compare         - uint8_t OutputRB1_Compare(OutputRB1_BufSizeType index, OutputRB1_ElementType...
**         Delete          - uint8_t OutputRB1_Delete(void);
**         NofElements     - OutputRB1_BufSizeType OutputRB1_NofElements(void);
**         NofFreeElements - OutputRB1_BufSizeType OutputRB1_NofFreeElements(void);
**         Deinit          - void OutputRB1_Deinit(void);
**         Init            - void OutputRB1_Init(void);
**
**     * Copyright (c) 2014-2017, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file OutputRB1.c
** @version 01.00
** @brief
**         This component implements a ring buffer for different integer data type.
*/         
/*!
**  @addtogroup OutputRB1_module OutputRB1 module documentation
**  @{
*/         

/* MODULE OutputRB1. */

#include "OutputRB1.h"

#if OutputRB1_CONFIG_REENTRANT
  #define OutputRB1_DEFINE_CRITICAL() CS1_CriticalVariable()
  #define OutputRB1_ENTER_CRITICAL()  CS1_EnterCritical()
  #define OutputRB1_EXIT_CRITICAL()   CS1_ExitCritical()
#else
  #define OutputRB1_DEFINE_CRITICAL() /* nothing */
  #define OutputRB1_ENTER_CRITICAL()  /* nothing */
  #define OutputRB1_EXIT_CRITICAL()   /* nothing */
#endif
static OutputRB1_ElementType OutputRB1_buffer[OutputRB1_CONFIG_BUF_SIZE]; /* ring buffer */
static OutputRB1_BufSizeType OutputRB1_inIdx;  /* input index */
static OutputRB1_BufSizeType OutputRB1_outIdx; /* output index */
static OutputRB1_BufSizeType OutputRB1_inSize; /* size data in buffer */
/*
** ===================================================================
**     Method      :  OutputRB1_Put (component RingBuffer)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Put(OutputRB1_ElementType elem)
{
  uint8_t res = ERR_OK;
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  if (OutputRB1_inSize==OutputRB1_CONFIG_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    OutputRB1_buffer[OutputRB1_inIdx] = elem;
    OutputRB1_inIdx++;
    if (OutputRB1_inIdx==OutputRB1_CONFIG_BUF_SIZE) {
      OutputRB1_inIdx = 0;
    }
    OutputRB1_inSize++;
  }
  OutputRB1_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Putn (component RingBuffer)
**     Description :
**         Put a number new element into the buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elem            - Pointer to new elements to be put into
**                           the buffer
**         nof             - number of elements
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Putn(OutputRB1_ElementType *elem, OutputRB1_BufSizeType nof)
{
  uint8_t res = ERR_OK;

  while(nof>0) {
    res = OutputRB1_Put(*elem);
    if (res!=ERR_OK) {
      break;
    }
    elem++; nof--;
  }
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Get (component RingBuffer)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Get(OutputRB1_ElementType *elemP)
{
  uint8_t res = ERR_OK;
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  if (OutputRB1_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = OutputRB1_buffer[OutputRB1_outIdx];
    OutputRB1_inSize--;
    OutputRB1_outIdx++;
    if (OutputRB1_outIdx==OutputRB1_CONFIG_BUF_SIZE) {
      OutputRB1_outIdx = 0;
    }
  }
  OutputRB1_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Getn (component RingBuffer)
**     Description :
**         Get a number elements into a buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * buf             - Pointer to buffer where to store the
**                           elements
**         nof             - number of elements
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Getn(OutputRB1_ElementType *buf, OutputRB1_BufSizeType nof)
{
  uint8_t res = ERR_OK;

  while(nof>0) {
    res = OutputRB1_Get(buf);
    if (res!=ERR_OK) {
      break;
    }
    buf++; nof--;
  }
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_NofElements (component RingBuffer)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
OutputRB1_BufSizeType OutputRB1_NofElements(void)
{
  return OutputRB1_inSize;
}

/*
** ===================================================================
**     Method      :  OutputRB1_NofFreeElements (component RingBuffer)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
OutputRB1_BufSizeType OutputRB1_NofFreeElements(void)
{
  return (OutputRB1_BufSizeType)(OutputRB1_CONFIG_BUF_SIZE-OutputRB1_inSize);
}

/*
** ===================================================================
**     Method      :  OutputRB1_Init (component RingBuffer)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void OutputRB1_Init(void)
{
  OutputRB1_inIdx = 0;
  OutputRB1_outIdx = 0;
  OutputRB1_inSize = 0;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Clear (component RingBuffer)
**     Description :
**         Clear (empty) the ring buffer.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void OutputRB1_Clear(void)
{
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  OutputRB1_Init();
  OutputRB1_EXIT_CRITICAL();
}

/*
** ===================================================================
**     Method      :  OutputRB1_Peek (component RingBuffer)
**     Description :
**         Returns an element of the buffer without removiing it.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Peek(OutputRB1_BufSizeType index, OutputRB1_ElementType *elemP)
{
  uint8_t res = ERR_OK;
  int idx; /* index inside ring buffer */
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  if (index>=OutputRB1_CONFIG_BUF_SIZE) {
    res = ERR_OVERFLOW; /* asking for an element outside of ring buffer size */
  } else if (index<OutputRB1_inSize) {
    idx = (OutputRB1_outIdx+index)%OutputRB1_CONFIG_BUF_SIZE;
    *elemP = OutputRB1_buffer[idx];
  } else { /* asking for an element which does not exist */
    res = ERR_RXEMPTY;
  }
  OutputRB1_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Compare (component RingBuffer)
**     Description :
**         Compares the elements in the buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to elements to compare with
**         nof             - number of elements to compare
**     Returns     :
**         ---             - zero if elements are the same, -1 otherwise
** ===================================================================
*/
uint8_t OutputRB1_Compare(OutputRB1_BufSizeType index, OutputRB1_ElementType *elemP, OutputRB1_BufSizeType nof)
{
  uint8_t cmpResult = 0;
  uint8_t res;
  OutputRB1_ElementType val;

  while(nof>0) {
    res = OutputRB1_Peek(index, &val);
    if (res!=ERR_OK) { /* general failure? */
      cmpResult = (uint8_t)-1; /* no match */
      break;
    }
    if (val!=*elemP) { /* mismatch */
      cmpResult = (uint8_t)-1; /* no match */
      break;
    }
    elemP++; index++; nof--;
  }

  return cmpResult;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Deinit (component RingBuffer)
**     Description :
**         Driver de-initialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/**
void OutputRB1_Deinit(void)
{
  ** Function is implemented as macro in the header file
}
*/
/*
** ===================================================================
**     Method      :  OutputRB1_Delete (component RingBuffer)
**     Description :
**         Removes an element from the buffer
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Delete(void)
{
  uint8_t res = ERR_OK;
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  if (OutputRB1_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    OutputRB1_inSize--;
    OutputRB1_outIdx++;
    if (OutputRB1_outIdx==OutputRB1_CONFIG_BUF_SIZE) {
      OutputRB1_outIdx = 0;
    }
  }
  OutputRB1_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  OutputRB1_Update (component RingBuffer)
**     Description :
**         Updates the data of an element.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t OutputRB1_Update(OutputRB1_BufSizeType index, OutputRB1_ElementType *elemP)
{
  uint8_t res = ERR_OK;
  int idx; /* index inside ring buffer */
  OutputRB1_DEFINE_CRITICAL();

  OutputRB1_ENTER_CRITICAL();
  if (index>=OutputRB1_CONFIG_BUF_SIZE) {
    res = ERR_OVERFLOW; /* asking for an element outside of ring buffer size */
  } else if (index<OutputRB1_inSize) {
    idx = (OutputRB1_outIdx+index)%OutputRB1_CONFIG_BUF_SIZE;
    OutputRB1_buffer[idx] = *elemP; /* replace element */
  } else { /* asking for an element which does not exist */
    res = ERR_RXEMPTY;
  }
  OutputRB1_EXIT_CRITICAL();
  return res;
}

/* END OutputRB1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
