%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (DataIndicationPacket)
%;**     Description :
%;**         Event in case data packet received.
%include Common\GeneralParameters.inc(27)
%;**         sRxPacket%ParsRxPacket %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine