%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ReadBlock)
%;**     Description :
%;**         Reads a block of memory from the EEPROM.
%include Common\GeneralParameters.inc(27)
%;**         addr%Paraddr %>27 - 
%;**       * data%Pardata %>27 - 
%;**         size%Parsize %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
