%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (btSetIAMStr)
%;**     Description :
%;**         Sets the Inquire Access Mode string
%include Common\GeneralParameters.inc(27)
%;**       * iam%Pariam %>27 - Pointer to new Inquire Access Mode string
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine