%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (btFindDeviceFromAuthenticatedDeviceListStr)
%;**     Description :
%;**         Find Device from Authenthicated Device List
%include Common\GeneralParameters.inc(27)
%;**       * addr%Paraddr %>27 - Pointer to address in NAP,UAP,LAP format
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine