%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetErrorString)
%;**     Description :
%;**         Returns for a given error code the error string describing
%;**         the problem.
%include Common\GeneralParameters.inc(27)
%;**         errorNo%ParerrorNo %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error string
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine