%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (btSetUARTParameterStr)
%;**     Description :
%;**         Sets the UART parameter.
%include Common\GeneralParameters.inc(27)
%;**       * param%Parparam %>27 - Pointer to new UART parameter string
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine