%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (btSetScanningParameterStr)
%;**     Description :
%;**         Sets the scanning parameters
%include Common\GeneralParameters.inc(27)
%;**       * param%Parparam %>27 - Pointer to string with the parameters.
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine