%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (StdIOSendChar)
%;**     Description :
%;**         StdIO handler to sends a character 
%include Common\GeneralParameters.inc(27)
%;**         ch%Parch %>27 - character to send
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine