%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (btSetCoDStr)
%;**     Description :
%;**         Sets the Class of Device string
%include Common\GeneralParameters.inc(27)
%;**       * classStr%ParclassStr %>27 - Pointer to new class of device
%;** %>29 string
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine