%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawFilledBox)
%;**     Description :
%;**         Draws a filled box with the given color
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x coordinate
%;**         y%Pary %>27 - 
%;**         w%Parw %>27 - width
%;**         h%Parh %>27 - height
%;**         color%Parcolor %>27 - color to be used
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine