%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (NegPixel)
%;**     Description :
%;**         Negates a pixel
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x coordinate
%;**         y%Pary %>27 - y coordinate
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine