%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnRelease)
%;**     Description :
%;**         Event called when an electrode release is detected.
%include Common\GeneralParameters.inc(27)
%;**         electrodeNr%ParelectrodeNr %>27 - electrode index (starting
%;** %>29 with zero)
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine