%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ScanButton)
%;**     Description :
%;**         Scans the sensors and raises the appropriate events
%include Common\GeneralParameters.inc(27)
%;**         ButtonNr%ParButtonNr %>27 - Button index, starting with zero.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine