%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Enable)
%;**     Description :
%;**         Enables the specifed electrode
%include Common\GeneralParameters.inc(27)
%;**         electrodeNr%ParelectrodeNr %>27 - electrode index (starting
%;** %>29 with zero)
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine