%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetTemperature)
%;**     @brief
%;**         Gets the temperature from memory. 
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         uint8_t sensor_index%>27 - Index of the sensor to get the temperature 
%;**         %>29 value. 
%;**         @return
%;**         int32_t %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
