%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (isBusy)
%;**     @brief
%;**         Returns TRUE if there are a operation in progress. 
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         bool %>27 - Returns TRUE if the device is busy, and FALSE if 
%;**         its ready to operate. 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
