%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (RenameFile)
%;**     Description :
%;**         Renames a file
%include Common\GeneralParameters.inc(27)
%;**         srcFileName%ParsrcFileName %>27 - Source file name
%;**         dstFileName%PardstFileName %>27 - Destination file name
%;**         io%Pario %>27 - Pointer to I/O handler
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine