%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Method)
%;**     Description :
%;**         Put a formatted string to the file
%include Common\GeneralParameters.inc(27)
%;**         Variable_1%ParVariable_1 %>27 - Pointer to the file object
%;**         str%Parstr %>27 - Pointer to the format string
%;**         Variable_2%ParVariable_2 %>27 - Optional arguments...
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine