%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (errMsg)
%;**     Description :
%;**         Returns for a given FatFs error code a string
%include Common\GeneralParameters.inc(27)
%;**         errNo%ParerrNo %>27 - FatFs error code
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine