%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (close)
%;**     Description :
%;**         Close a file
%include Common\GeneralParameters.inc(27)
%;**         fp%Parfp %>27 - Pointer to the open file object structure to
%;** %>29 be closed.
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine