%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (rename)
%;**     Description :
%;**         Delete a file or directory
%include Common\GeneralParameters.inc(27)
%;**         path_old%Parpath_old %>27 - Pointer to old object name
%;**         path_new%Parpath_new %>27 - Pointer to new object name
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine