%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Deinit)
%;**     Description :
%;**         Method to deinitialize the device driver
%include Common\GeneralParameters.inc(27)
%;**       * DeviceDataPtr%ParDeviceDataPtr %>27 - Pointer to RTOS
%;** %>29 structure
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine