%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (vPortFree)
%;**     Description :
%;**         Frees a memory block previously allocated with pvPortMalloc()
%include Common\GeneralParameters.inc(27)
%;**       * pv%Parpv %>27 - Pointer to data
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine