%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Move)
%;**     Description :
%;**         Sends a mouse move
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x move offset
%;**         y%Pary %>27 - y move offset
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine