%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Click)
%;**     Description :
%;**         Sends a button press event followed by a release event.
%include Common\GeneralParameters.inc(27)
%;**         buttonMask%ParbuttonMask %>27 - mask of buttons
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine