%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Notify_Callback)
%;**     Description :
%;**         Method to handle PSTN Sub Class callbacks
%include Common\GeneralParameters.inc(27)
%;**         controller_ID%Parcontroller_ID %>27 - controller ID
%;**         event_type%Parevent_type %>27 - value of the event
%;**         val%Parval %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
