%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Message)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         action%Paraction %>27 - Set of action bits, e.g. MOUSE_LEFT
%;**         x%Parx %>27 - x offset for move
%;**         y%Pary %>27 - y offset  for move
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine