%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnError)
%;**     Description :
%;**         Hook called in case of an error
%include Common\GeneralParameters.inc(27)
%;**         error%Parerror %>27 - Error code
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
