%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawBox)
%;**     Description :
%;**         Draws a rectangle line box
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x left upper coordinate
%;**         y%Pary %>27 - y left upper coordinate
%;**         width%Parwidth %>27 - width in pixels
%;**         height%Parheight %>27 - height in pixels
%;**         lineWidth%ParlineWidth %>27 - width of the line
%;**         color%Parcolor %>27 - color for the box
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine