%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawCircle)
%;**     Description :
%;**         Draws a circle using the Bresenham method
%include Common\GeneralParameters.inc(27)
%;**         x0%Parx0 %>27 - x start coordinate
%;**         y0%Pary0 %>27 - y start coordinate
%;**         radius%Parradius %>27 - Radius of the circle
%;**         color%Parcolor %>27 - color to be used for the line
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine