%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (XorPixel)
%;**     Description :
%;**         Xors a single pixel in the display.
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - Pixel x position.
%;**         y%Pary %>27 - Pixel y position.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine