%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawHLine)
%;**     Description :
%;**         Draws a horizontal line
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x left upper coordinate
%;**         y%Pary %>27 - y left upper coordinate
%;**         length%Parlength %>27 - Length of line in pixels
%;**         color%Parcolor %>27 - color to be used to fill the box.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine