%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Write_ReadDummy)
%;**     Description :
%;**         Writes to the bus, but does not read.
%include Common\GeneralParameters.inc(27)
%;**         val%Parval %>27 - value to put on the bus
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine