%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnDateSet)
%;**     Description :
%;**         called in the event of a date set
%include Common\GeneralParameters.inc(27)
%;**         day%Parday %>27 - the new day
%;**         month%Parmonth %>27 - the new month
%;**         year%Paryear %>27 - the new year
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine