%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetDir)
%;**     Description :
%;**         Sets the direction of the pin (input or output)
%include Common\GeneralParameters.inc(27)
%;**         Dir%ParDir %>27 - FALSE: input, TRUE: output
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine