%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PutVal)
%;**     Description :
%;**         Sets the pin value
%include Common\GeneralParameters.inc(27)
%;**         Val%ParVal %>27 - Value to set. FALSE/logical '0' or
%;** %>29 TRUE/logical '1'
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine