%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (AddTicks)
%;**     Description :
%;**         Same as AddTick(), but multiple ticks can be added in one
%;**         step.
%include Common\GeneralParameters.inc(27)
%;**         nofTicks%ParnofTicks %>27 - Number of ticks to be added
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine