%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetBytesPerLine)
%;**     Description :
%;**         Sets the number of bytes per line for the Dump shell command
%include Common\GeneralParameters.inc(27)
%;**         nofBytesPerLine%ParnofBytesPerLine %>27 - Number of bytes
%;** %>29 per line
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine