%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetDisplayOrientation)
%;**     Description :
%;**         Sets the display orientation
%include Common\GeneralParameters.inc(27)
%;**         newOrientation%ParnewOrientation %>27 - new orientation to
%;** %>29 be used
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine