%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (UseDisplay)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         display%Pardisplay %>27 - Has to be either 1 (top display,
%;** %>29 using E1) or 2 (bottom display, using E2)
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine