%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetByte)
%;**     Description :
%;**         returns TRUE if everything is ok, otherwise false.
%include Common\GeneralParameters.inc(27)
%;**         doRx%PardoRx %>27 - 
%;**         doTx%PardoTx %>27 - 
%;**         txData%PartxData %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine