%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetThreshold)
%;**     Description :
%;**         Sets the threshold value. A lower threshold means that less
%;**         light is required to trigger the sensor.
%include Common\GeneralParameters.inc(27)
%;**         value%Parvalue %>27 - Threshold value to be used.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
