%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnStatus)
%;**     Description :
%;**         Event is called on communiation status change
%include Common\GeneralParameters.inc(27)
%;**         status%Parstatus %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
