%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetFastReadMode0)
%;**     Description :
%;**         Turns the F_READ (Fast Read Mode) on or off
%include Common\GeneralParameters.inc(27)
%;**         on%Paron %>27 - if to turn the F_READ mode on or off
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine