%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetUserOffsetCorrection)
%;**     Description :
%;**         Sets the user offset correction values
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x offset
%;**         y%Pary %>27 - y offset
%;**         z%Parz %>27 - z offset
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine