%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetDirection)
%;**     Description :
%;**         Set the direction of the motor (forward or backward)
%include Common\GeneralParameters.inc(27)
%;**         forward%Parforward %>27 - 0 for forward, 1 for backward.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine