%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetVal)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         ratio%Parratio %>27 - PWM ratio value, in the range from 0
%;** %>29 (stop) to 0xffff (full speed)
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine