%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Gselect)
%;**     Description :
%;**         Allows to select different g sensitivity levels.
%include Common\GeneralParameters.inc(27)
%;**         gSelect%PargSelect %>27 - Pass 0 for 1.5g, 1 for 2g, 3 for
%;** %>29 4g and 4 for 6g sensitivity. The driver
%;** %>29 header file defines the values as macros as
%;** %>29 well.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine