%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetZmg)
%;**     Description :
%;**         Returns the Z value in milli g
%include Common\GeneralParameters.inc(27)
%;**       * accelZ%ParaccelZ %>27 - Pointer to the Z-accel value im
%;** %>29 milli g
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
