%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetXmg)
%;**     Description :
%;**         Returns the X value in milli g
%include Common\GeneralParameters.inc(27)
%;**       * accelX%ParaccelX %>27 - Pointer to the X-accel value im
%;** %>29 milli g
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
