%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Deinit)
%;**     Description :
%;**         Counterpart to Init() method. 
%include Common\GeneralParameters.inc(27)
%;**     Returns     :
%;**         uint8_t %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
