%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnPress)
%;**     Description :
%;**         Event for a button pressed. You can disable this event if
%;**         you are not interested in it in order to save code size.
%include Common\GeneralParameters.inc(27)
%;**         button%Parbutton %>27 - Button number, in the range 0 to 7.
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine