%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Display)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         firstDataRow%ParfirstDataRow %>27 - Location of data for
%;** %>29 first update row.
%;**         firstImageRow%ParfirstImageRow %>27 - First physical display
%;** %>29 row to display.
%;**         numRows%ParnumRows %>27 - Number of rows to update.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine