%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ProgramEvent)
%;**     @brief
%;**          
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         uint16_t key%>27 - Key to identificate the event, applies only 
%;**         %>29 if OProgramEvent is enabled. (Valid range 0 
%;**         %>29 - 31) 
%;**         @return
%;**         bool %>27 - Returns false if the program buffer is full. 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
