%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnWaitEnd)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**       * key%Parkey %>27 - Key to identificate the source of the
%;** %>29 event.
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine