%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (add_CRC)
%;**     @brief
%;**         Adds a bit to CRC accumulator. 
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         uint8_t bit_value%>27 -  
%;**         @return
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
