%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (add_CRC)
%;**     Description :
%;**         Adds a bit to CRC accumulator.
%include Common\GeneralParameters.inc(27)
%;**       * bit_value%Parbit_value %>27 - Bit to add to CRC accumulator.
%;**       * bit_value%Parbit_value %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine