%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetBytes)
%;**     @brief
%;**          
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         uint8_t _bytes%>27 -  
%;**         @param
%;**         uint8_t count%>27 -  
%;**         @return
%;**         bool %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
