%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnProgramEvent)
%;**     @brief
%;**          
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         int8_t key%>27 - Key to identificate the source of the event. 
%;**         @return
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
