%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Count)
%;**     @brief
%;**         Returns the number of elements stored on input buffer that are 
%;**         ready to read. 
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         uint8_t %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
