%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (NegOutputBit)
%;**     Description :
%;**         Negates a bit on the output register.
%include Common\GeneralParameters.inc(27)
%;**         bitNo%ParbitNo %>27 - Bit number, starting with 0
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine