%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ClrVal)
%;**     Description :
%;**         Clears (set to zero) the output value. It is equivalent to
%;**         the [PutVal(FALSE)]. This method is available only if the
%;**         direction = _[output]_.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine