%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetContrast)
%;**     Description :
%;**         Sets the display contrast.
%include Common\GeneralParameters.inc(27)
%;**         contrast%Parcontrast %>27 - Contrast value, must be in the
%;** %>29 range of  0 >= x < 128
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine