%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetMode)
%;**     Description :
%;**         Sets the mode of the display (if inverted or not).
%include Common\GeneralParameters.inc(27)
%;**         inverted%Parinverted %>27 - Pass TRUE to have the display
%;** %>29 operate in inverted mode, FALSE for normal
%;** %>29 mode.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine