%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (xTraceOpenLabel)
%;**     Description :
%;**         Open/create symbol to use as user event handle for related
%;**         user events (conceptually like a file handle)
%include Common\GeneralParameters.inc(27)
%;**       * label%Parlabel %>27 - Pointer to label
%;**     Returns     :
%;**         ---%RetVal %>27 - trace label
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine