%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnTraceWrap)
%;**     Description :
%;**         Called for trace ring buffer wrap around. This gives the
%;**         application a chance to dump the trace buffer.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine