%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (vTracePrintF)
%;**     Description :
%;**         Advanced user event - like printf (but limited formatting
%;**         support - will improve)
%include Common\GeneralParameters.inc(27)
%;**         eventLabel%PareventLabel %>27 - trace label
%;**       * formatStr%ParformatStr %>27 - Pointer to format string
%;**         Variable_1%ParVariable_1 %>27 - open parameter list
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine