%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (vTraceUserEvent)
%;**     Description :
%;**         Simple user event - store a label, created using
%;**         xTraceOpenLabel
%include Common\GeneralParameters.inc(27)
%;**         eventLabel%PareventLabel %>27 - trace label for the user
%;** %>29 event
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine