%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (vTraceSetTimerFrequency)
%;**     Description :
%;**         Use this to define the frequency of the timer/counter used
%;**         for timestamping (in Hz)
%include Common\GeneralParameters.inc(27)
%;**         frequency%Parfrequency %>27 - frequency
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine