%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Set_Td)
%;**     Description :
%;**         Change the Td parameter. 
%include Common\GeneralParameters.inc(27)
%;**         float t%>27 - New Td value. 
%;**     Returns     :
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
