%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Set_Ti)
%;**     Description :
%;**         Change the Ti parameter. 
%include Common\GeneralParameters.inc(27)
%;**         float t%>27 - New Ti value. 
%;**     Returns     :
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
