%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPoint)
%;**     Description :
%;**         Specifies the value to be reached by the PID controller.
%include Common\GeneralParameters.inc(27)
%;**         value%Parvalue %>27 - The setpoint value.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
