%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Set_K)
%;**     Description :
%;**         Change the K parameter. 
%include Common\GeneralParameters.inc(27)
%;**         float k%>27 - New K value. 
%;**     Returns     :
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
