%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPos)
%;**     Description :
%;**         Sets the position information. Can be used as well to reset
%;**         the position information.
%include Common\GeneralParameters.inc(27)
%;**         pos%Parpos %>27 - Position value to be set.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine