%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnItemGet)
%;**     Description :
%;**         Optional event created for every item removed with the Get()
%;**         method.
%include Common\GeneralParameters.inc(27)
%;**         elem%Parelem %>27 - item which gets removed
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine