%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnItemPut)
%;**     Description :
%;**         Optional event created for every item added with the Put()
%;**         method.
%include Common\GeneralParameters.inc(27)
%;**         elem%Parelem %>27 - item which gets added
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine