%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Get)
%;**     Description :
%;**         Removes an element from the buffer
%include Common\GeneralParameters.inc(27)
%;**       * elemP%ParelemP %>27 - Pointer to where to store the received
%;** %>29 element
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
