%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnEvent)
%;**     Description :
%;**         Event created for various radio states, like timeout, ack
%;**         received, data sent, ...
%include Common\GeneralParameters.inc(27)
%;**         event%Parevent %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine