%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnDateSet)
%;**     Description :
%;**         Event called when the date is set through the shell
%include Common\GeneralParameters.inc(27)
%;**         day%Parday %>27 - 
%;**         month%Parmonth %>27 - 
%;**         year%Paryear %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine