%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnError)
%;**     Description :
%;**         Event called in case of an error
%include Common\GeneralParameters.inc(27)
%;**         errorCode%ParerrorCode %>27 - 
%;**       * iteratorInfo%PariteratorInfo %>27 - Pointer to parser info
%;** %>29 struct
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine