%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPWMDuty)
%;**     Description :
%;**         Sets the servo PWM duty cycle
%include Common\GeneralParameters.inc(27)
%;**         dutyUs%PardutyUs %>27 - Duty cycle in microseconds
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine