%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PWMusToPos8)
%;**     Description :
%;**         Transforms a micro-second PWM time into 8bit position
%include Common\GeneralParameters.inc(27)
%;**         us%Parus %>27 - us PWM time
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine