%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetStdio)
%;**     Description :
%;**         Sets an StdIO structure which is returned by GetStdio()
%include Common\GeneralParameters.inc(27)
%;**         stdio%Parstdio %>27 - New stdio structure to be used.
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine