%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ReadChar)
%;**     Description :
%;**         Reads a character (blocking)
%include Common\GeneralParameters.inc(27)
%;**       * c%Parc %>27 - Pointer to character to be used to store the
%;** %>29 result
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
