%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PrintPrompt)
%;**     Description :
%;**         Prints the prompt to the stdOut channel
%include Common\GeneralParameters.inc(27)
%;**       * io%Pario %>27 - Pointer to IO to be used
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
