%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetEvents)
%;**     Description :
%;**         Sets one or more events (logical OR) to be processed by the
%;**         next HandleEvents() call
%include Common\GeneralParameters.inc(27)
%;**         events%Parevents %>27 - The set of events to have generated.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine