%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ClearEvent)
%;**     Description :
%;**         Clears one event (number). If the event is not set, then the
%;**         function has no effect.
%include Common\GeneralParameters.inc(27)
%;**         event%Parevent %>27 - The event number to be cleared.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine