%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (AppHandleEvent)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         event%Parevent %>27 - Event (event number) to be processed.
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine