%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MLMESetMC13192TmrPrescale)
%;**     Description :
%;**         Set MC13192 timer frequency
%include Common\GeneralParameters.inc(27)
%;**         u8Freq%Paru8Freq %>27 - Frequency value enumeration (0-7)
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine