%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MLMERXEnableRequest)
%;**     Description :
%;**         Set the receiver ON (with optional timeout)
%include Common\GeneralParameters.inc(27)
%;**         psRxPacket%ParpsRxPacket %>27 - 
%;**         u32Timeout%Paru32Timeout %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine