%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MLMEScanRequest)
%;**     Description :
%;**         Scan the enabled channels for energy
%include Common\GeneralParameters.inc(27)
%;**         flags%Parflags %>27 - 
%;**       * pu8ChannelScan%Parpu8ChannelScan %>27 - Pointer to 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine