%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MLMEMC13192PAOutputAdjust)
%;**     Description :
%;**         Adjust the Output power of the transmitter
%include Common\GeneralParameters.inc(27)
%;**         u8PaValue%Paru8PaValue %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine