%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PLMEEnableMC13192Timer1)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         u32CounterValue%Paru32CounterValue %>27 - timer value
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine