%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PLMEMC13192XtalAdjust)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         u8TrimValue%Paru8TrimValue %>27 - trim value
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine