%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PLMESetTrxStateRequest)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         u8ReqMode%Paru8ReqMode %>27 - Operational mode
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine