%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PLMESetTimeRequest)
%;**     Description :
%;**         Get the transceiver timer value.
%include Common\GeneralParameters.inc(27)
%;**         u32RequestedTime%Paru32RequestedTime %>27 - time value
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine