%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PLMEMC13192FEGainAdjust)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         i8GainValue%Pari8GainValue %>27 - Gain compensation
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine