%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (OpenWindow)
%;**     Description :
%;**         Opens a window inside the display we want to write to.
%include Common\GeneralParameters.inc(27)
%;**         x0%Parx0 %>27 - 
%;**         y0%Pary0 %>27 - 
%;**         x1%Parx1 %>27 - 
%;**         y1%Pary1 %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine