%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (WriteCommandWord)
%;**     Description :
%;**         Sends a word as command
%include Common\GeneralParameters.inc(27)
%;**         cmd%Parcmd %>27 - the command to be sent
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine