%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetKey)
%;**     Description :
%;**         Specify a security key
%include Common\GeneralParameters.inc(27)
%;**       * pBuffer%ParpBuffer %>27 - Pointer to the security key
%;**         u8Length%Paru8Length %>27 - Length of the security key
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine