%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (LeaveCounter)
%;**     Description :
%;**         To be called to return the counter. Note that a counter
%;**         always should be returned so it can be reused.
%include Common\GeneralParameters.inc(27)
%;**         handle%Parhandle %>27 - Counter handle
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine