%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Reset)
%;**     Description :
%;**         Resets the counter value and return the value just prior to
%;**         the call.
%include Common\GeneralParameters.inc(27)
%;**         handle%Parhandle %>27 - Counter handle
%;**         nofTicks%ParnofTicks %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Value of counter before reset.
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine