%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Value)
%;**     Description :
%;**         Return the current value of the counter (in ticks)
%include Common\GeneralParameters.inc(27)
%;**         handle%Parhandle %>27 - Handle of the timeout counter
%;**     Returns     :
%;**         ---%RetVal %>27 - none
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine