%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnEvent)
%;**     Description :
%;**         Event called touch screen events, like touched, untouched
%;**         etc.
%include Common\GeneralParameters.inc(27)
%;**         event%Parevent %>27 - 
%;**         x%Parx %>27 - x coordinate
%;**         y%Pary %>27 - y coordinate
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine