%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OSTaskIdleHook)
%;**     Description :
%;**         This function is called by the idle task.  This hook has
%;**         been added to allow you to do such things as STOP the CPU to
%;**         conserve power.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine