%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (OSStart)
%;**     Description :
%;**         This function is used to start the multitasking process
%;**         which lets uC/OS-II manages the task that you have created.
%;**         Before you can call OSStart(), you MUST have called OSInit()
%;**         and you MUST have created at least one task.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine