%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OSInitHookBegin)
%;**     Description :
%;**         This function is called by OSInit() at the beginning of
%;**         OSInit(). Note(s) : 1) Interrupts are enabled during this
%;**         call.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine