%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OSTaskStatHook)
%;**     Description :
%;**         This function is called every second by uC/OS-II's
%;**         statistics task.  This allows your application to add
%;**         functionality to the statistics task.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine