%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OSTCBInitHook)
%;**     Description :
%;**         This function is called on initialization of a task control
%;**         block.
%include Common\GeneralParameters.inc(27)
%;**       * ptcb%Parptcb %>27 - ptcp is a pointer to the task control
%;** %>29 block of the task being initialized.
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine