%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetUserMsgHandler)
%;**     Description :
%;**         Sets the user application callback for the widget.
%include Common\GeneralParameters.inc(27)
%;**       * button%Parbutton %>27 - Pointer to button
%;**         handler%Parhandler %>27 - Message handler
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine