%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (CreateButton)
%;**     Description :
%;**         Creates a new button
%include Common\GeneralParameters.inc(27)
%;**       * parent%Parparent %>27 - Pointer to parent element
%;**       * widget%Parwidget %>27 - Pointer to element
%;**         x%Parx %>27 - x position
%;**         y%Pary %>27 - y position
%;**       * txt%Partxt %>27 - Pointer to button text
%;**         handler%Parhandler %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine