%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetUserAppCallback)
%;**     Description :
%;**         Sets the user application callback for the button.
%include Common\GeneralParameters.inc(27)
%;**       * button%Parbutton %>27 - Pointer to button
%;**         callback%Parcallback %>27 - Name of callback
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine