%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetText)
%;**     Description :
%;**         Sets the button text and adopts the button size.
%include Common\GeneralParameters.inc(27)
%;**       * widget%Parwidget %>27 - Pointer to button widget
%;**         txt%Partxt %>27 - text for button
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine