%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (CheckBoxSet)
%;**     Description :
%;**         Sets the check status of a check box
%include Common\GeneralParameters.inc(27)
%;**       * checkBox%ParcheckBox %>27 - Pointer to checkbox
%;**         checked%Parchecked %>27 - The new value of the check box
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine