%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawFilledCircle)
%;**     Description :
%;**         Paints a filled circle in the element
%include Common\GeneralParameters.inc(27)
%;**       * element%Parelement %>27 - Pointer to element
%;**         x%Parx %>27 - x position
%;**         y%Pary %>27 - y postion
%;**         radius%Parradius %>27 - radius of the circle
%;**         color%Parcolor %>27 - color of the circle
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
