%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (EnableElementSelection)
%;**     Description :
%;**         Enables an element so it can be selected
%include Common\GeneralParameters.inc(27)
%;**       * elem%Parelem %>27 - Pointer to element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine