%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetBackgroundColor)
%;**     Description :
%;**         Changes the header background color
%include Common\GeneralParameters.inc(27)
%;**       * header%Parheader %>27 - Pointer to header
%;**         color%Parcolor %>27 - backround color
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine