%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ResizeIcon)
%;**     Description :
%;**         Resize the icon widget based on header content.
%include Common\GeneralParameters.inc(27)
%;**       * widget%Parwidget %>27 - Pointer to header widget
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine