%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ChangeIconFgColor)
%;**     Description :
%;**         Changes the foreground color of an icon
%include Common\GeneralParameters.inc(27)
%;**       * icon%Paricon %>27 - Pointer to icon
%;**         fgColor%ParfgColor %>27 - new color of icon
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine