%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MsgPaintAllElements)
%;**     Description :
%;**         Sends a PAINT message to all elements in the tree and list.
%include Common\GeneralParameters.inc(27)
%;**       * rootElement%ParrootElement %>27 - Pointer to the root element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine