%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PrevElement)
%;**     Description :
%;**         Finds the previous element of a sub tree
%include Common\GeneralParameters.inc(27)
%;**       * ppElement%ParppElement %>27 - Pointer to pointer element,
%;** %>29 used as input and output
%;**       * stopElement%ParstopElement %>27 - Pointer to element, used
%;** %>29 as highest possible element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
