%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ProcessTouch)
%;**     Description :
%;**         Processes a touch state change on a given position.
%include Common\GeneralParameters.inc(27)
%;**         touched%Partouched %>27 - If there is a touch at the given
%;** %>29 position
%;**         x%Parx %>27 - X position
%;**         y%Pary %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine