%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SendMessage)
%;**     Description :
%;**         Sends a message to an element.
%include Common\GeneralParameters.inc(27)
%;**         kind%Parkind %>27 - 
%;**       * element%Parelement %>27 - Pointer to element
%;**         pData%ParpData %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine