%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetUserAppCallback)
%;**     Description :
%;**         Sets the user application callback for the slider.
%include Common\GeneralParameters.inc(27)
%;**       * slider%Parslider %>27 - Pointer to slider
%;**         callback%Parcallback %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine