%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetValue)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**       * slider%Parslider %>27 - Pointer to slider
%;**     Returns     :
%;**         ---%RetVal %>27 - Returns the value of the slider
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine