%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetValue)
%;**     Description :
%;**         Sets the value of the slider
%include Common\GeneralParameters.inc(27)
%;**       * slider%Parslider %>27 - Pointer to slider
%;**         value%Parvalue %>27 - Value of the slider
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine