%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetUserMsgHandler)
%;**     Description :
%;**         Set additional user message handler.
%include Common\GeneralParameters.inc(27)
%;**       * textW%PartextW %>27 - Pointer to text widget
%;**         handler%Parhandler %>27 - Callback to be used
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine