%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetBgColor)
%;**     Description :
%;**         Change the background color of the text.
%include Common\GeneralParameters.inc(27)
%;**       * txtw%Partxtw %>27 - Pointer to text widget
%;**         bgColor%ParbgColor %>27 - text background color
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine