%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetText)
%;**     Description :
%;**         Returns a pointer to the text
%include Common\GeneralParameters.inc(27)
%;**       * widget%Parwidget %>27 - Pointer to widget
%;**     Returns     :
%;**         ---%RetVal %>27 - pointer to text string
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine