%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Resize)
%;**     Description :
%;**         Resize the widget area based on the text in it.
%include Common\GeneralParameters.inc(27)
%;**       * widget%Parwidget %>27 - Pointer to text widget
%;**     Returns     :
%;**         ---%RetVal %>27 - error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine