%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetTextFgColor)
%;**     Description :
%;**         Change the foreground color of the text.
%include Common\GeneralParameters.inc(27)
%;**       * txtw%Partxtw %>27 - Pointer to text widget
%;**         fgColor%ParfgColor %>27 - text color
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine