%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetBackgroundColor)
%;**     Description :
%;**         Changes the window background color.
%include Common\GeneralParameters.inc(27)
%;**       * window%Parwindow %>27 - Pointer to window widget
%;**         color%Parcolor %>27 - Background color for window
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine