%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (WindowAddHeader)
%;**     Description :
%;**         Add header to window, for movable window
%include Common\GeneralParameters.inc(27)
%;**       * window%Parwindow %>27 - Pointer to window structure
%;**       * header%Parheader %>27 - Pointer to header
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine