%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MakeWindowMovable)
%;**     Description :
%;**         Makes a window movable, this window must have a header
%include Common\GeneralParameters.inc(27)
%;**       * window%Parwindow %>27 - Pointer to window structure
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine