%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnMouseMove)
%;**     Description :
%;**         Event for mouse movement
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - x position value
%;**         y%Pary %>27 - y position value
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine