%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnMouseButton)
%;**     Description :
%;**         Event called on mouse button event
%include Common\GeneralParameters.inc(27)
%;**         button0%Parbutton0 %>27 - value of button 0 (0 for not
%;** %>29 pressed, one for pressed)
%;**         button1%Parbutton1 %>27 - value of button 1 (0 for not
%;** %>29 pressed, one for pressed)
%;**         button2%Parbutton2 %>27 - value of button 2 (0 for not
%;** %>29 pressed, one for pressed)
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine