%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ByteRev32)
%;**     Description :
%;**         Performs a byte reverse on a 32bit value
%include Common\GeneralParameters.inc(27)
%;**         val%Parval %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - reverted value
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine