%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (stack_size)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         pattern%Parpattern %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - stack size
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine