%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnEvent)
%;**     Description :
%;**         Called on every key press
%include Common\GeneralParameters.inc(27)
%;**         ch%Parch %>27 - ASCII code of key pressed
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine