%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnKeyboardRawKey)
%;**     Description :
%;**         Event called in the event of a keyboard event (press or
%;**         release)
%include Common\GeneralParameters.inc(27)
%;**       * keys%Parkeys %>27 - Pointer to key information
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine