%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (HeaderSetLine)
%;**     Description :
%;**         Initializes the header for the window
%include Common\GeneralParameters.inc(27)
%;**       * header%Parheader %>27 - Pointer to header
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine