%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ScrollMenuGetSelection)
%;**     Description :
%;**         Returns the index of the currently selected item in the
%;**         scroll menu
%include Common\GeneralParameters.inc(27)
%;**       * scrollMenu%ParscrollMenu %>27 - Pointer to scrollMenu
%;**     Returns     :
%;**         ---%RetVal %>27 - the currently selected item index
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine