%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (CheckBoxIsChecked)
%;**     Description :
%;**         Returns TRUE or FALSE, depending on the check box state
%include Common\GeneralParameters.inc(27)
%;**       * checkBox%ParcheckBox %>27 - Pointer to check box
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine