%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ChangeTextFgColor)
%;**     Description :
%;**         Changes the text foreground color.
%include Common\GeneralParameters.inc(27)
%;**       * elem%Parelem %>27 - Pointer to element
%;**         fgColor%ParfgColor %>27 - text color
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine