%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (setOtherFont)
%;**     Description :
%;**         Function to set an other font.
%include Common\GeneralParameters.inc(27)
%;**       * getChar%PargetChar %>27 - Pointer to the GetFontChar
%;** %>29 function of the previous font Bean.
%;**       * get_BoxHight%Parget_BoxHight %>27 - Pointer to the
%;** %>29 GetBoxHight function of the previouse font
%;** %>29 Bean.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine