%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ChangeTextBgColor)
%;**     Description :
%;**         Changes the text background color.
%include Common\GeneralParameters.inc(27)
%;**       * elem%Parelem %>27 - Pointer to element
%;**         bgColor%ParbgColor %>27 - text background color
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine