%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ScrollMenuNofItems)
%;**     Description :
%;**         Returns the number of selectable items in the scroll menu
%include Common\GeneralParameters.inc(27)
%;**       * scrollMenu%ParscrollMenu %>27 - Pointer to scrollMenu
%;**     Returns     :
%;**         ---%RetVal %>27 - number of list items
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine