%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (getTemp)
%;**     Description :
%;**         This method return the stored temperatures.
%include Common\GeneralParameters.inc(27)
%;**       * pUtiTemperatures%ParpUtiTemperatures %>27 - Pointer to
%;** %>29 result of measured temperatures from UTI
%;**         selectTemp%ParselectTemp %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine