%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (strlen)
%;**     Description :
%;**         Wrapper to the standard strlen() function.
%include Common\GeneralParameters.inc(27)
%;**         str%Parstr %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - size of strinig
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine