%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (measureCycle)
%;**     Description :
%;**         This method measure the time of phases in one cycle of the
%;**         UTI signal.
%include Common\GeneralParameters.inc(27)
%;**       * pPhasesStartExt%ParpPhasesStartExt %>27 - Pointer to first
%;** %>29 phase of cycle
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine