%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Waitns)
%;**     Description :
%;**         Wait for a specified time in nano seconds.
%include Common\GeneralParameters.inc(27)
%;**         ns%Parns %>27 - How many ns the function has to wait
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine