%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Waitms)
%;**     Description :
%;**         Wait for a specified time in milliseconds.
%include Common\GeneralParameters.inc(27)
%;**         ms%Parms %>27 - How many milliseconds the function has to
%;** %>29 wait
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine