%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Waitus)
%;**     Description :
%;**         Wait for a specified time in microseconds.
%include Common\GeneralParameters.inc(27)
%;**         us%Parus %>27 - How many microseconds the function has to
%;** %>29 wait
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine