%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (xvformat)
%;**     Description :
%;**         Printf() like format function
%include Common\GeneralParameters.inc(27)
%;**         outchar%Paroutchar %>27 - Function pointer to the function
%;** %>29 to output one char.
%;**       * arg%Pararg %>27 - Argument for the output function.
%;**         fmt%Parfmt %>27 - Format options for the list of parameters.
%;**         args%Parargs %>27 - List of parameters
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine