%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Put)
%;**     Description :
%;**         Turns the LED on or off.
%include Common\GeneralParameters.inc(27)
%;**         val%Parval %>27 - value to define if the LED has to be on or
%;** %>29 off.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine