%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (IsLeapYear)
%;**     Description :
%;**         Returns true if a given year is a leap year
%include Common\GeneralParameters.inc(27)
%;**         year%Paryear %>27 - Year, in the YYYY format.
%;**     Returns     :
%;**         ---%RetVal %>27 - If the year is a leap year or not.
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine